[[pages]]
path = "app.py"
name = "News Feed"
icon = "ğŸ "

[[pages]]
path = "pages/graph.py"
name = "Graph"
icon = "ğŸ“Š"

[[pages]]
path = "pages/event_details.py"
name = "Event Details"
icon = "ğŸ“"

[[pages]]
path = "pages/potential_events_horizon.py"
name = "Potential Events Per Horizon"
icon = "ğŸ”®" 